# Blue-Green — two full deployments run simultaneously
# Switch traffic instantly by patching the service selector
# Rollback is instant — patch selector back to blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-backend-blue
  annotations:
    role: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      tier: backend
      slot: blue
  template:
    metadata:
      labels:
        app: aceest
        tier: backend
        slot: blue
    spec:
      containers:
      - name: aceest-backend
        image: sasanmanpreet91/aceest-fitness-gym-api:18
        ports:
        - containerPort: 5005
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-backend-green
  annotations:
    role: new-version
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      tier: backend
      slot: green
  template:
    metadata:
      labels:
        app: aceest
        tier: backend
        slot: green
    spec:
      containers:
      - name: aceest-backend
        image: sasanmanpreet91/aceest-fitness-gym-api:21
        ports:
        - containerPort: 5005
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
