# Canary — 9 stable + 1 canary = ~10% traffic to new version
# K8s load balances proportionally to replica count
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-backend-stable
  annotations:
    role: stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: aceest
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: aceest
        tier: backend
        track: stable
    spec:
      containers:
      - name: aceest-backend
        image: sasanmanpreet91/aceest-fitness-gym-api:18
        ports:
        - containerPort: 5005
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-backend-canary
  annotations:
    role: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      tier: backend
      track: canary
  template:
    metadata:
      labels:
        app: aceest
        tier: backend
        track: canary
    spec:
      containers:
      - name: aceest-backend
        image: sasanmanpreet91/aceest-fitness-gym-api:21
        ports:
        - containerPort: 5005
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
